### ISSUE TITLE
Mingw64 build crashes if you use thread count 20 (parameter -t 20)

### ISSUE THREAD

**Issue by Orava2** [Orava2/hodlminer#2]
Cygwin build works ok but Mingw build causes segmentation fault if you use e.g. 20 or 3 threads.

`[Switching to Thread 10168.0x130c]
0x0000000000412a0b in scanhash_hodl (threadNumber=threadNumber@entry=2, totalThreads=<optimized out>,
    pdata=pdata@entry=0x44e2f9a0, Garbage=0x4820040, ptarget=ptarget@entry=0x44e2fa20,
    hashes_done=hashes_done@entry=0x44e2f97c) at hodl.c:61
61                  memcpy(Cache[n].dwords, Garbage + k + n, GARBAGE_SLICE_SIZE);
segmentation fault at line 61 hodl.c: memcpy(Cache[n].dwords, Garbage + k + n, GARBAGE_SLICE_SIZE);`

**Comment by Orava2** [comment]
fixed in source code

**Comment by Orava2** [comment]
Thread counts 3, 6, 7, 19, 20, 21, 27, 30, 60, 63 are causing problems.

There is another part in the source code that causes problems in Linux (Mint Linux)

```
[2018-05-21 21:42:15] 3 miner threads started, using 'hodl' algorithm.
 
Thread 5 "hodlminer" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffb0e88700 (LWP 19138)]
sha512Compute32b_parallel (data=data@entry=0x7fffb0e87420,
    digest=digest@entry=0x7fffb0e87460) at sha512_avx2.c:142
142         digest[6][i] = _mm256_extract_epi64(context[1].h[i], 2);
(gdb) backtrace
#0  sha512Compute32b_parallel (data=data@entry=0x7fffb0e87420,
    digest=digest@entry=0x7fffb0e87460) at sha512_avx2.c:142
#1  0x0000000000414fea in GenerateGarbageCore (MidHash=0x7fffb0e87400,
    ThreadCount=<optimized out>, ThreadID=16777218, Garbage=0x7fffb1e8b000)
    at hodl.c:31
#2  GenRandomGarbage (Garbage=0x7fffb1e8b000, totalThreads=<optimized out>,
    pdata=pdata@entry=0x7fffb0e87630, thr_id=thr_id@entry=2) at hodl.c:171
#3  0x000000000040de29 in miner_thread (userdata=0x645c80) at cpu-miner.c:1310
#4  0x00007ffff79526ba in start_thread (arg=0x7fffb0e88700)
    at pthread_create.c:333
#5  0x00007ffff768841d in clone ()
    at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
```
